### ISSUE TITLE
Why Not In Order

### ISSUE THREAD

**Issue by telase** [VinhPham26/HLS-Downloader#1]
cmd works on all links at the same time.
why not one and in order?
Once the file is finished in single download, the other should begin

**Comment by VinhPham26** [comment]
sorry for so slow response, at the time I create this app, I did think about this but since I create this app to download anime, making it to download at the same time is a lot faster than only download one.

**Comment by VinhPham26** [comment]
I will make another button for choosing between download all at the same time and in order

**Comment by telase** [comment]
ok , thank you so much

**Comment by VinhPham26** [comment]
I made changed and release new version

**Comment by telase** [comment]
thank you
